name: Terraform CI/CD

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Terraform Init
        run: terraform init
        working-directory: ./Environment/Dev

      - name: Terraform Format Check
        run: terraform fmt -check
        working-directory: ./Environment/Dev

      - name: Terraform Validate
        run: terraform validate
        working-directory: ./Environment/Dev

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./Environment/Dev
